### ISSUE TITLE
[FE] To-Do

### ISSUE THREAD

**Issue by dididy** [petlab-dev/app-prototype#55]
- [x] Change banner image properly
- [x] Change name Petsome to Catmate
- [x] Change color detect range hsv(200 < h < 300)
- [x] Add danger color catalog on indicator screen on colorpicker component
